// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv2B4zTCQZ8TidDwnGrBGT_JQYjICdTmI',
    appId: '1:790168940521:web:03e264a6f9a7a9a1146578',
    messagingSenderId: '790168940521',
    projectId: 'flutterproject-b684b',
    authDomain: 'flutterproject-b684b.firebaseapp.com',
    storageBucket: 'flutterproject-b684b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAULfs4DeEiM6aKiNp_C89bos2jibUXPZo',
    appId: '1:790168940521:android:c20605b54649ce40146578',
    messagingSenderId: '790168940521',
    projectId: 'flutterproject-b684b',
    storageBucket: 'flutterproject-b684b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYP7D2xY3gTcmyqKaHTXHT6kDeigbSk5s',
    appId: '1:790168940521:ios:e43ae537542345b7146578',
    messagingSenderId: '790168940521',
    projectId: 'flutterproject-b684b',
    storageBucket: 'flutterproject-b684b.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYP7D2xY3gTcmyqKaHTXHT6kDeigbSk5s',
    appId: '1:790168940521:ios:cb4c06dc92811fde146578',
    messagingSenderId: '790168940521',
    projectId: 'flutterproject-b684b',
    storageBucket: 'flutterproject-b684b.appspot.com',
    iosBundleId: 'com.example.flutterProject.RunnerTests',
  );
}
